# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  # --- 알림 전송 공통 함수 ---
  def send_discord_message(status: nil, exception: nil, bundle_id: nil)
    webhook_url = ENV["DISCORD_WEBHOOK_URL"]
    return unless webhook_url # URL이 없으면 스킵

    # 빌드 정보 가져오기 (xcodeproj 경로 명시)
    proj_path = "Projects/todaktodot/todaktodot.xcodeproj"
    version = get_version_number(xcodeproj: proj_path, target: "todaktodot")
    build = get_build_number(xcodeproj: proj_path)
    branch = ENV["GITHUB_REF_NAME"] || "unknown"

    env_name =
     if bundle_id&.include?(".dev")
       "투닥투닷 Dev"
     else
       "투닥투닷"
     end
     
    if status == "success"
      title = "✅ iOS #{env_name} 배포 성공"
      color = 306699 # 파란색
      description = "새로운 버전이 TestFlight에 업로드되었습니다."
    else
      title = "❌ iOS #{env_name} 배포 실패"
      color = 15158332 # 빨간색
      description = "빌드 중 에러가 발생했습니다: #{exception}"
    end

    payload = {
      embeds: [{
        title: title,
        description: description,
        color: color,
        fields: [
          { name: "Version", value: "#{version} (#{build})", inline: true }
        ],
        footer: { text: "todaktodot-iOS" },
        timestamp: Time.now.utc.iso8601
      }]
    }.to_json

    sh("curl -H 'Content-Type: application/json' -d '#{payload}' #{webhook_url}")
  end

  # 모든 작업 성공 후 실행
  after_all do |lane|
    send_discord_message(
      status: "success",
      bundle_id: Actions.lane_context[:BUNDLE_ID]
    )
  end

  # 에러 발생 시 실행
  error do |lane, exception|
    send_discord_message(
      status: "failure",
      exception: exception,
      bundle_id: Actions.lane_context[:BUNDLE_ID]
    )
  end

  desc "PR 빌드용"
  lane :ci do
    scan(
      workspace: "todaktodotWorkspace.xcworkspace",
      scheme: "todaktodot",
      clean: true
    )
  end
  
  desc "Release 배포"
  lane :beta do
    deploy(
      scheme: "todaktodot",
      bundle_id: "info.todaktodot",
      display_name: "투닥투닷"
    )
  end
  
  desc "Dev 배포"
  lane :beta_dev do
    deploy(
      scheme: "todaktodot",
      bundle_id: "info.todaktodot.dev",
      display_name: "투닥투닷 dev"
    )
  end
  
  desc "TestFlight 배포"
  lane :deploy do |options|
    bundle_id = options[:bundle_id] || "info.todaktodot"
    display_name = options[:display_name] || "투닥투닷"
    scheme = options[:scheme] || "todaktodot"
    Actions.lane_context[:BUNDLE_ID] = bundle_id
    version = ENV["VERSION"]
    
    setup_ci if is_ci
    
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_filepath: "./AuthKey.p8"
    )

    match(
      type: "appstore",
      app_identifier: bundle_id,
      readonly: true,
      git_url: "https://github.com/todaktodot/fastlane-match-iOS.git"
    )

    increment_version_number(
      version_number: version,
      xcodeproj: "Projects/todaktodot/todaktodot.xcodeproj"
    )

    latest_build = latest_testflight_build_number(
      api_key: api_key,
      app_identifier: bundle_id
    ) || 0

    increment_build_number(
      build_number: latest_build + 1,
      xcodeproj: "Projects/todaktodot/todaktodot.xcodeproj"
    )

    profile_name = Actions.lane_context[SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING][bundle_id]

    build_app(
      workspace: "todaktodotWorkspace.xcworkspace",
      scheme: scheme,
      clean: false,
      skip_package_dependencies_resolution: true,
      include_symbols: false,
      include_bitcode: false,
      export_method: "app-store",
      xcargs: [
        "CODE_SIGN_STYLE=Manual",
        "CODE_SIGN_IDENTITY='Apple Distribution'",
        "INFOPLIST_KEY_CFBundleDisplayName='#{display_name}'",
        "PROVISIONING_PROFILE_SPECIFIER='#{profile_name}'"
      ].join(" "),
      export_options: {
        method: "app-store",
        signingStyle: "manual",
        provisioningProfiles: {
          bundle_id => profile_name
        }
      }
    )

    if bundle_id == "info.todaktodot"
    	upload_to_app_store(
     	 api_key: api_key,
     	 app_identifier: bundle_id,
     	 skip_metadata: true,
     	 skip_screenshots: true,
     	 submit_for_review: true,
     	 automatic_release: false,
     	 force: true,
	 run_precheck_before_submit: false
      )
    else
      upload_to_testflight(
        app_identifier: bundle_id,
         skip_waiting_for_build_processing: true
      )
    end
  end
end
