# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "PR 빌드용"
  lane :ci do
    scan(
      workspace: "todaktodotWorkspace.xcworkspace",
      scheme: "todaktodot",
      clean: true
    )
  end

  desc "TestFlight 배포"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_filepath: "./AuthKey.p8"
    )

    match(
      type: "appstore",
      readonly: true
    )

    # 1. 최신 빌드 넘버 가져오기
    latest_build = latest_testflight_build_number(
      api_key: api_key,
      app_identifier: "info.todaktodot"
    ) || 0

    # 2. 빌드 넘버 증가 (xcodeproj 경로 명시)
    increment_build_number(
      build_number: latest_build + 1,
      xcodeproj: "Projects/todaktodot/todaktodot.xcodeproj"
    )

    # 3. 앱 빌드
    build_app(
      workspace: "todaktodotWorkspace.xcworkspace",
      scheme: "todaktodot",
      export_method: "app-store",
      clean: true,
      export_options: {
        provisioningProfiles: {
          "info.todaktodot" => "match AppStore info.todaktodot"
        }
      }
    )

    # 4. 테스트플라이트 업로드
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end