name: iOS Beta Deploy

on:
  push:
    branches: [ "CI/CD" ]
  workflow_dispatch:

concurrency:
  group: ios-beta
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1️⃣ 코드 체크아웃
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '26.3'

      # 2️⃣ Ruby & Bundler 설치
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true # 캐시를 사용하면 속도가 빨라집니다.

      - name: Cache mise tools
        uses: actions/cache@v4
        with:
          path: |
            ~/.local/share/mise
            ~/.cache/mise
          key: ${{ runner.os }}-mise-${{ hashFiles('.mise.toml', '.tool-versions') }}

      - name: Cache Tuist
        uses: actions/cache@v4
        with:
          path: |
            ~/.tuist
            ~/.local/share/tuist
            ~/Library/Caches/tuist
          key: ${{ runner.os }}-tuist-${{ hashFiles('Tuist/**/*.swift') }}
          restore-keys: |
            ${{ runner.os }}-tuist-

      - name: Cache SwiftPM
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Developer/Xcode/SourcePackages
            ~/Library/Caches/org.swift.swiftpm
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved', 'Tuist/**/*.swift') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Setup mise
        uses: jdx/mise-action@v2

      - name: Install Tools via mise
        run: mise install

      - name: Install Tuist Dependencies
        run: mise exec -- tuist install

      - name: Create xcconfig files
        run: |
          mkdir -p Projects/todaktodot/Config

          printf "" > Projects/todaktodot/Config/Debug.xcconfig

          printf "KAKAO_APP_KEY = %s\nKAKAO_URL_KEY = %s\nGOOGLE_URL_KEY = %s\nTODAKTODOT_API = %s\nPRODUCT_BUNDLE_IDENTIFIER = %s\n" \
          "${{ secrets.KAKAO_APP_KEY }}" \
          "${{ secrets.KAKAO_URL_KEY }}" \
          "${{ secrets.GOOGLE_URL_KEY }}" \
          "${{ secrets.TODAKTODOT_API }}" \
          "${{ secrets.PRODUCT_BUNDLE_IDENTIFIER }}" \
          > Projects/todaktodot/Config/Release.xcconfig

      - name: Decode GoogleService-Info.plist
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_INFO_PLIST_BASE64 }}" | base64 --decode > Projects/todaktodot/Resources/GoogleService-Info-Release.plist

      - name: Generate project
        run: mise exec -- tuist generate
          
      - name: Create App Store Connect API Key
        run: |
          echo "${{ secrets.APP_STORE_CONNECT_API_KEY }}" | base64 --decode > AuthKey.p8

      - name: Run Fastlane Beta
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          FASTLANE_USER: ${{ secrets.APPLE_ID }}
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          
#        run: bundle exec fastlane beta
        
      - name: Print xcodebuild log
        if: failure()
        run: |
          ls -R /Users/runner/Library/Logs || true
          
      - name: Print gym log
        if: failure()
        run: |
          find /Users/runner -name "*.log" | grep gym || true
          
